In [1]:
!pip install transformers==4.41.2 #accelerate==0.31.0

In [2]:
from transformers import AutoModelForCausalLM, AutoTokenizer

In [4]:
model = AutoModelForCausalLM.from_pretrained(
    'microsoft/Phi-3-mini-4k-instruct',
    device_map='cuda',
    torch_dtype='auto',
    trust_remote_code = True
)

tokenizer = AutoTokenizer.from_pretrained(
   'microsoft/Phi-3-mini-4k-instruct' 
)

config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

configuration_phi3.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-4k-instruct:
- configuration_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


modeling_phi3.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-4k-instruct:
- modeling_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


model.safetensors.index.json: 0.00B [00:00, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [5]:
prompt = "Write an email apologizing to Sarah for the tragic gardening mishap. Explain how it happened.<|assistant|>"

input_ids = tokenizer(prompt, return_tensors='pt').input_ids.to("cuda")
input_ids


tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292,   286,   728,   481, 29889, 12027,  7420,   920,
           372,  9559, 29889, 32001]], device='cuda:0')

In [6]:
input_ids.shape

torch.Size([1, 24])

In [7]:
# We are suppingng embeddings as inpput instead of text
# hence no need to tokenizer again
ouput = model.generate(input_ids=input_ids,
                       max_new_tokens=20)
ouput

tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292,   286,   728,   481, 29889, 12027,  7420,   920,
           372,  9559, 29889, 32001,  3323,   622, 29901,   317,  3742,   406,
          6225, 11763,   363,   278, 19906,   292,   341,   728,   481,    13,
            13,    13, 29928,   799]], device='cuda:0')

In [9]:
tokenizer.decode(ouput[0])

'Write an email apologizing to Sarah for the tragic gardening mishap. Explain how it happened.<|assistant|> Subject: Sincere Apologies for the Gardening Mishap\n\n\nDear'

In [12]:
len(ouput[0])

44

## Contextualied word embeddings

In [3]:
from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('microsoft/deberta-base')

model = AutoModel.from_pretrained('microsoft/deberta-base')

tokens = tokenizer('Hello world', return_tensors='pt')

output = model(**tokens)[0]

output

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/474 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/559M [00:00<?, ?B/s]

tensor([[[ 0.0473, -0.0435, -0.0812,  ...,  0.0121,  0.0395, -0.0462],
         [-1.1017, -0.7390, -0.7409,  ..., -0.4467,  0.3183, -0.4456],
         [ 1.0047,  0.6782, -0.4958,  ...,  0.2436, -0.3662,  0.5453],
         [ 0.2161,  0.0714, -0.1412,  ...,  0.0635,  0.1943,  0.0773]]],
       grad_fn=<AddBackward0>)

In [6]:
tokens['input_ids']

tensor([[    1, 31414,   232,     2]])

In [9]:
for token in tokens['input_ids'][0]: 
    print(tokenizer.decode(token))

[CLS]
Hello
 world
[SEP]


In [11]:
del(model)
del(tokens)

In [5]:
#!pip install -U accelerate

In [6]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-tranformer/all-mpnet-base-v2")

vector = model.encode("Best Movie Ever")

vector

RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
cannot import name 'clear_device_cache' from 'accelerate.utils.memory' (/usr/local/lib/python3.12/dist-packages/accelerate/utils/memory.py)

In [8]:
#!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 76.5 MB/s eta 0:00:00:00:0100:01


In [9]:
import gensim.downloader as api

model = api.load("glove-wiki-gigaword-50")

[==================================================] 100.0% 66.0/66.0MB downloaded


In [10]:
model.most_similar([model['king']], topn=11)

[('king', 1.0000001192092896),
 ('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542161345481873),
 ('throne', 0.7539914846420288),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953)]

## Recommending songs by embeddings

In [12]:
import pandas as pd
from urllib import request

# Get the playlist dataset file
data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

# Parse the playlist dataset file. Skip the first two lines as
# they only contain metadata
lines = data.read().decode("utf-8").split('\n')[2:]

# Remove playlists with only one song
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

In [15]:
playlists[:5], lines[:5]

([['0',
   '1',
   '2',
   '3',
   '4',
   '5',
   '6',
   '7',
   '8',
   '9',
   '10',
   '11',
   '12',
   '13',
   '14',
   '15',
   '16',
   '17',
   '18',
   '19',
   '20',
   '21',
   '22',
   '23',
   '24',
   '25',
   '26',
   '27',
   '28',
   '29',
   '30',
   '31',
   '32',
   '33',
   '34',
   '35',
   '36',
   '37',
   '38',
   '39',
   '40',
   '41',
   '2',
   '42',
   '43',
   '44',
   '45',
   '46',
   '47',
   '48',
   '20',
   '49',
   '8',
   '50',
   '51',
   '52',
   '53',
   '54',
   '55',
   '56',
   '57',
   '25',
   '58',
   '59',
   '60',
   '61',
   '62',
   '3',
   '63',
   '64',
   '65',
   '66',
   '46',
   '47',
   '67',
   '2',
   '48',
   '68',
   '69',
   '70',
   '57',
   '50',
   '71',
   '72',
   '53',
   '73',
   '25',
   '74',
   '59',
   '20',
   '46',
   '75',
   '76',
   '77',
   '59',
   '20',
   '43'],
  ['78',
   '79',
   '80',
   '3',
   '62',
   '81',
   '14',
   '82',
   '48',
   '83',
   '84',
   '17',
   '85',
   '86',
   '87',
   '88

In [16]:
# Load song metadata
songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split('\n')
songs = [s.rstrip().split('\t') for s in songs_file]
songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df = songs_df.set_index('id')
songs_df.head(10)

title       artist
id                                                                
0                        Gucci Time (w\/ Swizz Beatz)   Gucci Mane
1   Aston Martin Music (w\/ Drake & Chrisette Mich...    Rick Ross
2                       Get Back Up (w\/ Chris Brown)         T.I.
3                  Hot Toddy (w\/ Jay-Z & Ester Dean)        Usher
4                                        Whip My Hair       Willow
5                            Down On Me (w\/ 50 Cent)      Jeremih
6                                    Black And Yellow  Wiz Khalifa
7                                   Blowing Me Kisses   Soulja Boy
8                                         Lay It Down        Lloyd
9                       Good For My Money (w\/ Lloyd)    Baby Bash

In [19]:
songs_df.iloc[2172]

title     Fade To Black
artist        Metallica
Name: 2172 , dtype: object

In [17]:
print( 'Playlist #1:\n ', playlists[0], '\n')
print( 'Playlist #2:\n ', playlists[1])

Playlist #1:
  ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43'] 

Playlist #2:
  ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117',

In [18]:
from gensim.models import Word2Vec

model = Word2Vec(playlists, vector_size=32, window=20, negative=50, min_count=1, workers=4)
model

In [20]:
song_id = 2172
model.wv.most_similar(positive=str(song_id))

[('5549', 0.9973635673522949),
 ('3094', 0.997061550617218),
 ('2640', 0.996330976486206),
 ('2886', 0.9958697557449341),
 ('2849', 0.9955652952194214),
 ('2881', 0.9946438074111938),
 ('2976', 0.9944872260093689),
 ('6624', 0.9941015243530273),
 ('6640', 0.9934466481208801),
 ('3114', 0.9932973384857178)]

In [21]:
import numpy as np

def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive=str(song_id),topn=5)
    )[:,0]
    return  songs_df.iloc[similar_songs]

# Extract recommendations
print_recommendations(2172)

title         artist
id                                    
5549      November Rain  Guns N' Roses
3094   Breaking The Law   Judas Priest
2640      Red Barchetta           Rush
2886            The Zoo      Scorpions
2849   Run To The Hills    Iron Maiden