In [1]:
!pip install transformers==4.41.2 

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 102.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 69.4 MB/s eta 0:00:00:00:01
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.1
    Uninstalling tokenizers-0.22.1:
      Successfully uninstalled tokenizers-0.22.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.3
    Uninstalling transformers-4.57.3:
      Successfully uninstalled transformers-4.57.3


In [2]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3-mini-4k-instruct",
                                             device_map="cuda",
                                             torch_dtype="auto",
                                             trust_remote_code=True)

tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

generator = pipeline("text-generation",
                     model=model,
                     tokenizer=tokenizer,
                     return_full_text=False, #the prompt wont be returned but only the ouput of the model will be
                     max_new_tokens=500, #setting limit
                     do_sample=False)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

configuration_phi3.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-4k-instruct:
- configuration_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


modeling_phi3.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3-mini-4k-instruct:
- modeling_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


model.safetensors.index.json: 0.00B [00:00, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [3]:
model

Phi3ForCausalLM(
  (model): Phi3Model(
    (embed_tokens): Embedding(32064, 3072, padding_idx=32000)
    (embed_dropout): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0-31): 32 x Phi3DecoderLayer(
        (self_attn): Phi3Attention(
          (o_proj): Linear(in_features=3072, out_features=3072, bias=False)
          (qkv_proj): Linear(in_features=3072, out_features=9216, bias=False)
          (rotary_emb): Phi3RotaryEmbedding()
        )
        (mlp): Phi3MLP(
          (gate_up_proj): Linear(in_features=3072, out_features=16384, bias=False)
          (down_proj): Linear(in_features=8192, out_features=3072, bias=False)
          (activation_fn): SiLU()
        )
        (input_layernorm): Phi3RMSNorm()
        (resid_attn_dropout): Dropout(p=0.0, inplace=False)
        (resid_mlp_dropout): Dropout(p=0.0, inplace=False)
        (post_attention_layernorm): Phi3RMSNorm()
      )
    )
    (norm): Phi3RMSNorm()
  )
  (lm_head): Linear(in_features=3072, out_features=3206

In [4]:
prompt = 'The capital of france is'

input_ids = tokenizer(prompt, return_tensors='pt').input_ids

input_ids = input_ids.to("cuda")

model_output = model.model(input_ids)

model_output[0]

tensor([[[-0.3047,  1.1953,  0.2988,  ..., -0.3008,  0.6758,  0.1406],
         [-0.1338,  0.3184,  0.3926,  ...,  0.5508, -0.1318, -0.6055],
         [-0.5820,  1.0703,  1.5547,  ..., -0.4082,  0.2773,  0.4062],
         [-0.0272,  1.1484,  0.4395,  ...,  0.6836, -0.6758,  0.3828],
         [-0.4883,  1.0234,  0.7500,  ..., -0.1592,  0.2949, -0.3711],
         [-1.0156,  0.4082,  0.1123,  ...,  0.7500, -0.0571,  0.2490]]],
       device='cuda:0', dtype=torch.bfloat16, grad_fn=<MulBackward0>)

In [6]:
input_ids

tensor([[ 450, 7483,  310, 2524,  346,  338]], device='cuda:0')

In [8]:
tokenizer.decode(input_ids[0])

'The capital of france is'

In [5]:
model_output[0].shape

torch.Size([1, 6, 3072])

In [ ]:
lm_head_output = model.lm_head(model_output[0])
print(lm_head_output.shape)

#For each token in the input sequence, this is the generated probability for the entire vocab size of 32064
lm_head_output

torch.Size([1, 6, 32064])


tensor([[[24.7500, 24.8750, 22.7500,  ..., 19.0000, 19.0000, 19.0000],
         [31.1250, 31.5000, 26.0000,  ..., 26.0000, 26.0000, 26.0000],
         [31.5000, 28.8750, 31.1250,  ..., 26.2500, 26.2500, 26.2500],
         [13.0625, 10.1875, 12.3750,  ...,  8.5625,  8.5625,  8.5625],
         [33.2500, 32.0000, 35.0000,  ..., 27.7500, 27.7500, 27.7500],
         [28.1250, 26.8750, 25.5000,  ..., 19.0000, 19.0000, 19.0000]]],
       device='cuda:0', dtype=torch.bfloat16, grad_fn=<UnsafeViewBackward0>)

In [ ]:
# we need the probability after the last token "is" 
# Therefore we'll take -1 of the output to get the last token
lm_head_output[0,-1].shape

torch.Size([32064])

In [16]:
#amongst all these, we'll get argmax
max_prob_token = lm_head_output[0,-1].argmax(-1)
tokenizer.decode(max_prob_token)

'par'

tensor(3681, device='cuda:0')

In [48]:
second_max_prob_token = lm_head_output[0,-1].argsort(descending = True)[1]
tokenizer.decode(second_max_prob_token)

'Paris'